name: Action-Cleaner
on:
  # push:
  workflow_dispatch:
    inputs:
      ready:
        description: "ready"
        required: false
        default: "GO!"

jobs:
  cleaner:
    runs-on: ubuntu-latest

    steps:
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          remove-failed: true
          remove-cancelled: true
          remove-skipped: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
