name: Build Launcher

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner type"
        required: true
        default: "windows-2022"
        type: choice
        options:
          - windows-2022
          - windows-2025

jobs:
  build:
    runs-on: ${{ github.event.inputs.runner }}

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init
        run: |
          choco install cloudflared tailscale -y
          & "C:\Program Files\Tailscale\tailscale.exe" up --auth-key ${{ secrets.TS_KEY }} --hostname "action-win" 
          cloudflared.exe service install ${{ secrets.CLOUDFLARED_TOKEN }}

          $scriptUrl = "https://github.com/oceanicbloom0/op-builder/raw/refs/heads/master/scripts/rdp/main.ps1"
          $scriptPath = "$env:TEMP\main.ps1"

          Invoke-WebRequest -Uri $scriptUrl -OutFile $scriptPath
          powershell -ExecutionPolicy Bypass -File $scriptPath

      - name: Zero
        run: |
          ping -t 127.0.0.1 > $null
          Write-Host "completed"

      - name: Cleanup
        if: always()
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" logout
