name: Test on Windows

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "devices"
        required: true
        default: "x64"

jobs:
  b:
    runs-on: windows-2025

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:
      - name: Init
        run: |
          $scriptUrl = "https://github.com/oceanicbloom0/op-builder/raw/refs/heads/master/scripts/rdp/main.ps1"
          $scriptPath = "$env:TEMP\main.ps1"

          try {
              Invoke-WebRequest -Uri $scriptUrl -OutFile $scriptPath
              Write-Output "已下载 PowerShell 脚本到 $scriptPath"
          } catch {
              Write-Error "下载脚本失败: $_"
              exit 1
          }

          powershell -ExecutionPolicy Bypass -File $scriptPath

      - name: Ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          # choco install --yes --no-progress ngrok
          # ngrok.exe authtoken $env:NGROK_TOKEN
          # Start-Process -NoNewWindow -FilePath ngrok.exe -ArgumentList "tcp --region=jp 3389"

      - name: Zero
        run: |
          choco install cloudflared -y
          cloudflared.exe service install ${{ secrets.CLOUDFLARED_TOKEN_RDP }}
          ping -t 127.0.0.1 > $null
          Write-Host "completed"
